### ISSUE TITLE
8.1 update to 8.2 warning: VERGEN_SYSINFO_USER set to default  

### ISSUE THREAD

**Issue by luyikk** [rustyhorde/vergen#228] opened 2023-07-18 04:10 UTC
system:windows 11
vergen:8.2
rustc:1.70.0

warning: VERGEN_SYSINFO_USER set to default  

How to solve it？

**Comment by luyikk** [comment] 2023-07-25 02:10
> I'll take a look at this shortly. I've been away for the past week.
> 
> That output is generally caused because cannot successfully determine the user. The current logic looks up the current PID and checks the list of users knows about, then checks that list for the user associated with the process. If this fails for any reason (PID can't be found, user is restricted by OS) then you will get the default output. I've seen this happen commonly on Windows systems because getting the PID of the current process fails, but I've never seen in happen on Linux.`sysinfo``sysinfo`

I'm sure there's no problem with 8.1,occurred on 8.2.

**Comment by CraZySacX** [comment] 2023-11-05 21:43
Can you add `fail_on_error` to your `EmitBuilder` config to see if any additional insights can be gleaned.    I am unable to reproduce this on my Windows or Linux boxes.

![vergen-cl-windows](https://github.com/rustyhorde/vergen/assets/1423378/5a70097f-193d-4ea4-88c2-80995e0780ab)

**Comment by CraZySacX** [comment] 2024-01-15 01:57
Closing this as I can't reproduce.   If this is still happening, add your `build.rs` and vergen config from your `Cargo.toml` to the ticket and re-open.

**Closed by CraZySacX** 2024-01-15 01:57 UTC
